### PR TITLE
add popup titles for icon only buttons

### PR DESCRIPTION
**Pull request by circles-png**

### CODE REVIEW

**Review by dcndr — APPROVED** [review]
woah

**Comment by dcndr** [comment]
tooltips need to be added to new icon

**Comment by circles-png** [comment]
you can request changes but ok

**Comment by circles-png** [comment]
also there is no new icon in this branch/parallel universe

**Comment by dcndr** [comment]
yeah I forgor ab the icon until I saw the branch conflicts

**Pull request merged**
